### ISSUE TITLE
failed to select a version for `gtk`

### ISSUE THREAD

**Issue by jonas-schievink** [gtk-rs/gtk-test#19]
Trying to build master (ca736637064a8ba87a9d1d3713d05b5e52fa33d2) results in the following error:

```
error: failed to select a version for `gtk`.
    ... required by package `gtk-test v0.2.0 (/home/jonas/dev/gtk-test)`
versions that meet the requirements `*` are: 0.5.0

the package `gtk-test` depends on `gtk`, with features: `v3_10` but `gtk` does not have these features.
```

This might have been caused by the git dependencies getting out of date.

**Comment by GuillaumeGomez** [comment]
This is very likely. We removed a lot of features in those crates.

@sdroege We'll need to update this one as well. :3

**Comment by sdroege** [comment]
Yes it should just not use any feature flags anymore, those are the default now. Also the travis build needs to be updated: 1) multiple configurations not need (`GTK=...`) as they are not used in there at all, 2) 1.31 instead of 1.28
